In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from scipy.stats import norm

In [2]:
# Carregamento dos dados
dados = pd.read_csv('/content/E_commerce.csv')
dados

,Unnamed: 0,Email,Endereço,Avatar,Tempo_app,Tempo_site,Tempo_compra,Valor_da_venda
0,0,mstephenson@fernandez.com,"835 Frank Tunnel\nWrightmouth, MI 82180-9605",Violet,12.655651,39.577668,4.082621,587.951054
1,1,hduke@hotmail.com,"4547 Archer Common\nDiazchester, CA 06566-8576",DarkGreen,11.109461,37.268959,2.664034,392.204933
2,2,pallen@yahoo.com,"24645 Valerie Unions Suite 582\nCobbborough, D...",Bisque,11.330278,37.110597,4.104543,487.547505
3,3,riverarebecca@gmail.com,"1414 David Throughway\nPort Jason, OH 22070-1220",SaddleBrown,13.717514,36.721283,3.120179,581.852344
4,4,mstephens@davidson-herman.com,"14023 Rodriguez Passage\nPort Jacobville, PR 3...",MediumAquaMarine,12.795189,37.536653,4.446308,599.406092
...,...,...,...,...,...,...,...,...
495,495,lewisjessica@craig-evans.com,"4483 Jones Motorway Suite 872\nLake Jamiefurt,...",Tan,13.566160,36.417985,3.746573,573.847438
496,496,katrina56@gmail.com,"172 Owen Divide Suite 497\nWest Richard, CA 19320",PaleVioletRed,11.695736,37.190268,3.576526,529.049004
497,497,dale88@hotmail.com,"0787 Andrews Ranch Apt. 633\nSouth Chadburgh, ...",Cornsilk,11.499409,38.332576,4.958264,551.620145
498,498,cwilson@hotmail.com,"680 Jennifer Lodge Apt. 808\nBrendachester, TX...",Teal,12.391423,36.840086,2.336485,456.469510
499,499,hannahwilson@davidson.com,49791 Rachel Heights Apt. 898\nEast Drewboroug...,DarkMagenta,12.418808,35.771016,2.735160,497.778642

In [3]:
#Deletando coluna improdutiva
del dados ['Unnamed: 0']

In [4]:
#Checando se há valores ausentes
dados.isnull().sum()

Email             0
Endereço          0
Avatar            0
Tempo_app         0
Tempo_site        0
Tempo_compra      0
Valor_da_venda    0
dtype: int64

In [5]:
#Checando se há valores duplicados pelo identificador que nesse caso é o email
dados['Email'].duplicated().sum()

0

In [6]:
#Verificando o estado do dataframe
dados

,Email,Endereço,Avatar,Tempo_app,Tempo_site,Tempo_compra,Valor_da_venda
0,mstephenson@fernandez.com,"835 Frank Tunnel\nWrightmouth, MI 82180-9605",Violet,12.655651,39.577668,4.082621,587.951054
1,hduke@hotmail.com,"4547 Archer Common\nDiazchester, CA 06566-8576",DarkGreen,11.109461,37.268959,2.664034,392.204933
2,pallen@yahoo.com,"24645 Valerie Unions Suite 582\nCobbborough, D...",Bisque,11.330278,37.110597,4.104543,487.547505
3,riverarebecca@gmail.com,"1414 David Throughway\nPort Jason, OH 22070-1220",SaddleBrown,13.717514,36.721283,3.120179,581.852344
4,mstephens@davidson-herman.com,"14023 Rodriguez Passage\nPort Jacobville, PR 3...",MediumAquaMarine,12.795189,37.536653,4.446308,599.406092
...,...,...,...,...,...,...,...
495,lewisjessica@craig-evans.com,"4483 Jones Motorway Suite 872\nLake Jamiefurt,...",Tan,13.566160,36.417985,3.746573,573.847438
496,katrina56@gmail.com,"172 Owen Divide Suite 497\nWest Richard, CA 19320",PaleVioletRed,11.695736,37.190268,3.576526,529.049004
497,dale88@hotmail.com,"0787 Andrews Ranch Apt. 633\nSouth Chadburgh, ...",Cornsilk,11.499409,38.332576,4.958264,551.620145
498,cwilson@hotmail.com,"680 Jennifer Lodge Apt. 808\nBrendachester, TX...",Teal,12.391423,36.840086,2.336485,456.469510
499,hannahwilson@davidson.com,49791 Rachel Heights Apt. 898\nEast Drewboroug...,DarkMagenta,12.418808,35.771016,2.735160,497.778642

In [7]:
#Construindo um dataframe apenas com os valores numéricos
dados1 = pd.DataFrame(dados.iloc[:, 3:8].values, 
                      columns = ['Tempo_app', 'Tempo_site', 
                                 'Tempo_de_adesao', 'Total_gasto_anual'])

In [8]:
#Vizualizando
dados1

     Tempo_app  Tempo_site  Tempo_de_adesao  Total_gasto_anual
0    12.655651   39.577668         4.082621         587.951054
1    11.109461   37.268959         2.664034         392.204933
2    11.330278   37.110597         4.104543         487.547505
3    13.717514   36.721283         3.120179         581.852344
4    12.795189   37.536653         4.446308         599.406092
..         ...         ...              ...                ...
495  13.566160   36.417985         3.746573         573.847438
496  11.695736   37.190268         3.576526         529.049004
497  11.499409   38.332576         4.958264         551.620145
498  12.391423   36.840086         2.336485         456.469510
499  12.418808   35.771016         2.735160         497.778642

[500 rows x 4 columns]